version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - disagro-medical-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_KEY=6473dbe0-e691-4a1d-ada9-af7bf12afc2c
      - REACT_APP_SERVICES_URL=http://localhost:5000
    networks:
      - disagro-medical-network
networks:
  disagro-medical-network:
    driver: bridge
