version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - disagro-medical-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - disagro-medical-network
networks:
  disagro-medical-network:
    driver: bridge
